Mounight/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using Mounight.Models;
using SimpleImageGallery.Data;
using SimpleImageGallery.Data.Models;

namespace Mounight.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IImage _imageService;
        public GalleryController(IImage imageService)
        {
            _imageService = imageService;
        }
        public IActionResult Index()
        {
            var imageList = _imageService.GetAll();

            var model = new GalleryIndexModel()
            {
                Images = imageList,
                SearchQuery = ""
            };

            return View(model);
        }

        public IActionResult Detail(int id) 
        { 
            var image = _imageService.GetById(id);
            var model = new GalleryDetailModel()
            {
                Id = image.Id,
                Title = image.Title,
                CreatedOn = image.Created,
                Url = image.Url,
                Tags = image.Tags.Select(t => t.Description).ToList()
            };

            return View(model);
        }
    }
}

Mounight/Views/Gallery/Detail.cshtml
@model Mounight.Models.GalleryDetailModel

<div class="container">
	<div class="picture__group">
		<div class="picture__info">
			<div>@Model.Title</div>
			<span>@Model.CreatedOn</span>
		</div>

		<div class="picture__actions">
			<a class="button__light" asp-controller="Gallery" asp-action="Index">Back to Gallery</a>
			<a class="button__dark" asp-controller="Gallery" asp-action="Index" style="width: 140px;">Download</a>
		</div>
	</div>
	<div class="picture__top" style="background-image: url(@Model.Url)">
	</div>
</div>

Mounight/Views/Gallery/Index.cshtml
@model Mounight.Models.GalleryIndexModel

<div>
	<partial name="/Views/Shared/_HeroPartial.cshtml" />
	<div class="container">
		<h2 class="gallery__title">Our Gallery</h2>
		<div class="gallery">
			@foreach (var image in Model.Images)
			{
				<a asp-controller="Gallery" asp-action="Detail" asp-route-id="@image.Id">
					<div class="gallery__item" style="background-image: url(@image.Url)">
					</div>
				</a>
				
			}
		</div>
	</div>
</div>